name: 'Github Action for OpenSCAD'
author: 'Johannes Arnold'
description: 'Compile OpenSCAD in Docker'
inputs:
  root_file:
    description: 'The file to be compiled'
    default: '*.scad'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.root_file }}
