# action.yml
name: 'Github Action for OpenSCAD'
description: 'Compile OpenSCAD in Docker'
inputs:
  root_file:
    description: 'The file to be compiled'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.root_file }}
